### ISSUE TITLE
Add option to make overlay disappear completely

### ISSUE THREAD

**Issue by pocmo** [pocmo/WebCards#5]

**Comment by antlam** [comment]
<img width="574" alt="screen shot 2016-06-30 at 10 36 32 am" src="https://cloud.githubusercontent.com/assets/1994820/16498018/8f9350e4-3eae-11e6-9250-ac74c30b0374.png">

WIP still but having it behave similar to chat heads (for prototyping purposes) makes sense. 

I've deliberately put the "dismiss area" off to the bottom right since that's where most FAB buttons will be. This will hopefully help people from obstructing other apps' FAB buttons. 

But this may or may not be necessary – still worth prototyping to try out though.

**Comment by pocmo** [comment]
Okay, I just added the functionality. It's working but there is no visual indicator yet.

**Comment by pocmo** [comment]
So, this is the implementation with "dismiss area":

Video: https://www.youtube.com/watch?v=rqmJ9N7SxZ4

Screenshot:
![dismiss_area](https://cloud.githubusercontent.com/assets/89638/16518718/b1863384-3f84-11e6-88da-78fefc0cd3e0.png)

Values I used:
- The dismiss area is 150x150xp in the bottom right corner
- In the bottom right corner I draw a circle with a gradient from black to transparent and radius 150dp.
- The rectangle is 40x40dp and I draw it with 10dp margin
- The X is drawn in a 20x20dp rectangle
- I use a stroke width of 2dp
